spring:
  application:
    name: discovery
---
spring:
  profiles: discovery1
server:
  port: 10001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10002/eureka


---
spring:
  profiles: discovery2
server:
  port: 10002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka


---
spring:
  profiles: heroku-discovery1
eureka:
  instance:
    hostname: belajar-springcloud-discovery1.herokuapp.com
    non-secure-port: 80
  client:
    service-url:
      defaultZone: https://belajar-springcloud-discovery2.herokuapp.com/eureka/


---
spring:
  profiles:
eureka:
  instance:
    hostname: belajar-springcloud-discovery2.herokuapp.com
    non-secure-port: 80
  client:
    service-url:
      defaultZone: https://belajar-springcloud-discovery1.herokuapp.com/eureka/

