server:
  port: 8888

spring:
  profiles:
    active: git
  security:
    user:
      name: user
      password: password

  logging:
    level:
      org.springframework.cloud.config: DEBUG

  spring:
    profiles: git
    cloud:
      config:
        server:
          git:
            url: https://github.com/alfanherya/spring-cloud/config-store.git
            cloneOnStart: true
